#!/bin/bash

eval $(docker-machine env default)

if [[ $(docker ps | grep budgetless | wc -l) -gt 0 ]]; then
  docker kill budgetless >/dev/null 2>&1
fi

export $(cat env.local | grep -v '#')

ip=$(ipconfig getifaddr en0)

# https://stackoverflow.com/a/31249288/1467342
# https://gist.github.com/MauricioMoraes/87d76577babd4e084cba70f63c04b07d
# https://www.thegeekstuff.com/2014/02/enable-remote-postgresql-connection/
docker run --rm \
  --name budgetless \
  --add-host=host:$ip \
  -v $PWD:/var/app \
  -p $PORT:$PORT \
  budgetless ./start

